"""empty message

Revision ID: 94cadedb8e39
Revises: 40b84c8c6795
Create Date: 2018-01-24 14:20:03.391596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94cadedb8e39'
down_revision = '40b84c8c6795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_auths', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint('role_auths_ibfk_2', 'role_auths', type_='foreignkey')
    op.create_foreign_key(None, 'role_auths', 'roles', ['role_id'], ['id'])
    op.drop_column('role_auths', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_auths', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role_auths', type_='foreignkey')
    op.create_foreign_key('role_auths_ibfk_2', 'role_auths', 'users', ['user_id'], ['id'])
    op.drop_column('role_auths', 'role_id')
    # ### end Alembic commands ###
