"""empty message

Revision ID: d5673cb13ba2
Revises: fe799aa51132
Create Date: 2018-01-30 19:05:49.265283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5673cb13ba2'
down_revision = 'fe799aa51132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face')
    # ### end Alembic commands ###
